PACKAGE=httprest

.PHONY: help
help:
	@echo "venv        -> prepare VENV with all dependencies installed"
	@echo "test        -> run tests"
	@echo "clean       -> remove autogenerated files (venv, cache, etc.)"
	@echo "coverage    -> run tests coverage and prepare HTML report"

venv:
	poetry install

.PHONY: testdeps
testdeps:
	poetry install --with test

.PHONY: test
test:
	pytest -svvv tests

.PHONY: coverage
coverage:
	pytest --cov-report html --cov=$(PACKAGE) --cov-report=html --cov-report=term tests

.PHONY: lintdeps
lintdeps:
	poetry install --no-root --only=lint

.PHONY: lint
lint:
	black $(PACKAGE) tests --check
	pydocstyle $(PACKAGE)/** tests/**
	flake8 $(PACKAGE) tests
	pylint --rcfile=pyproject.toml $(PACKAGE) tests
	mypy $(PACKAGE) tests
	pip-audit

.PHONY: testall
testall: lint test

.PHONY: clean
clean:
	rm -rf build _build dist *.egg-info .coverage htmlcov .nox
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	poetry env remove --all
	py3clean . -v
